---
# tasks file for influx
- name: Create namespace
  shell:
    cmd: 'kubectl create namespace {{ influx_namespace }}'
  become: true
  ignore_errors: true
- name: Ensure manifests folder exits
  file:
    path: '{{ manifest_folder }}'
    state: directory
- name: Render manifests
  template:
    src: '{{ item.src }}'
    dest: '{{ manifest_folder }}/{{ item.dest }}'
  with_items: '{{ influx_manifests }}'
- name: Apply manifests
  shell:
    cmd: 'kubectl apply -f {{ manifest_folder }}/{{ item.dest }} -n {{ influx_namespace }}'
  with_items: '{{ influx_manifests }}'