---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influx-data-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: {{influx_data_storage}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influx-config-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: {{influx_config_storage}}