---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influx
  labels:
    app: influx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influx
  template:
    metadata:
      labels:
        app: influx
    spec:
      containers:
      - name: influx
        image: {{influx_image}}
        ports:
        - containerPort: 8086
          name: influx
          protocol: TCP
        volumeMounts:
        #- name: influx-config
        #  mountPath: etc/influxdb2
        #- name: influx-data
        #  mountPath: /var/lib/influxdb2
        env:
        - name: INFLUXDB_DATABASE
          value: brewery
        - name: INFLUXDB_USERNAME
          value: root
        - name: INFLUXDB_PASSWORD
          value: root
      #volumes:
      #- name: influx-data
      #  persistentVolumeClaim:
      #    claimName: influx-data-claim
